version: '3.4'

services:
    
  catalogdb : 
    image: mongo
    
  catalogmicroservice.api:
    image: ${DOCKER_REGISTRY-}catalogmicroserviceapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogMicroservice.Api/Dockerfile
volumes:
  mongo_data :